services/web/easymail/models.py
from datetime import datetime
import string
from random import choices
from easymail import db ,login_manager,app
from flask_login import UserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model,UserMixin):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), unique=False, nullable=False)
    phone = db.Column(db.String(255), unique=False, nullable=True)
    email = db.Column(db.String(255),unique=True,nullable=False)
    password = db.Column(db.String(255),unique=False,nullable=False)
    role = db.Column(db.String(60),unique=False,nullable=False,server_default='free')
    confirmed = db.Column(db.Boolean, nullable=False, server_default='False')
    confirmed_on = db.Column(db.DateTime, nullable=True,server_default=db.func.now(), server_onupdate=db.func.now())
    deleted = db.Column(db.Boolean, nullable=False, server_default='False')
    created_at = db.Column(db.DateTime, server_default=db.func.now())
    updated_at = db.Column(db.DateTime, server_default=db.func.now(), server_onupdate=db.func.now())
    userEmails = db.relationship('Websites',backref="websites",lazy=True)

    def get_reset_token(self, expires_sec=1800):
        s = Serializer(app.config['SECRET_KEY'], expires_sec)
        return s.dumps({'user_id': self.id}).decode('utf-8')

    @staticmethod
    def verify_reset_token(token):
        s = Serializer(app.config['SECRET_KEY'])
        try:
            user_id = s.loads(token)['user_id']
        except:
            return None
        return User.query.get(user_id)

class Websites(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String(40000), unique=False, nullable=False)
    keyword = db.Column(db.String(4000), unique=False, nullable=False)
    deleted = db.Column(db.Boolean, nullable=False, server_default='False')
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)
    created_at = db.Column(db.DateTime, server_default=db.func.now())
    updated_at = db.Column(db.DateTime, server_default=db.func.now(), server_onupdate=db.func.now())
    emails = db.relationship('Emails', backref='websites',lazy=True)

class Emails(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), nullable=False, unique=False)
    website_id = db.Column(db.Integer, db.ForeignKey('websites.id'), nullable=True)
    created_at = db.Column(db.DateTime, server_default=db.func.now())
    updated_at = db.Column(db.DateTime, server_default=db.func.now(), server_onupdate=db.func.now())
    
db.create_all()

services/web/easymail/NewUsers/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField,TextAreaField,IntegerField
from wtforms.validators import DataRequired,Length,Email,EqualTo, ValidationError

from easymail.models import User

class RegistrationForm(FlaskForm):
   
    email = StringField('Email', validators=[DataRequired(),Length(min=4,max=60)])
   
    name = StringField('Name', validators=[DataRequired(),Length(max=20)])
    password = PasswordField('Hasło', validators=[DataRequired(),Length(min=8,max=86,message='Hasło musi mieć przynajmniej: 8 znaków, 1 duza literę i przynajmniej 1 jedną literę')])
    confirm_password = PasswordField('Powtórz hasło', validators=[DataRequired(),EqualTo('password','Hasła się nie zgadzają')])
   
    submit = SubmitField('Register')
    

    def validate_email(self,email):
        user = User.query.filter_by(email=email.data).all()
       
        if user:
            raise ValidationError('Uzytkownik istnieje')

class LoginForm(FlaskForm):
   
    email = StringField('Email', validators=[DataRequired()])
    password = PasswordField('Hasło', validators=[DataRequired()])
    submit = SubmitField('Login')
    remember = BooleanField('Zapamiętaj mnie')

class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Poproś o nowe hasło')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('Nie ma uztkownika o takim emailu. Zarejestruj się')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Hasło', validators=[DataRequired()])
    confirm_password = PasswordField('Potwierdź hasło',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Zresetuj hasło')

services/web/easymail/Panel/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField,TextAreaField,IntegerField, SelectField
from wtforms.validators import DataRequired,Length,Email,EqualTo, ValidationError

from easymail.models import User

### Creating submit form for searching keywords ###
class SearchForm(FlaskForm):
    keyword = StringField('Keyword',validators=[DataRequired()])
    number_of_links = IntegerField('Number',validators=[DataRequired()])
    country = SelectField('Country',choices=[('pl','Poland'),('en','England')])
    device = SelectField('Device',choices=[('desktop','Desktop'),('tablet','Tablet'),('mobile','Mobile')])
    domain = SelectField('Domain',choices=[('pl','pl'),('com','com'),('de','de')])
    engine = SelectField('Engine',choices=[('google','Google'),('baidu','Baidu'),('yahoo','Yahoo!')])
    submit = SubmitField('Search')

services/web/easymail/Main/routes.py
from flask import render_template, url_for, flash, redirect,request,Blueprint
from easymail import app,db,bcrypt
Main=Blueprint('Main',__name__)


###### Main Page ##### 
@Main.route('/',methods=['GET','POST'])

def main():
    return redirect(url_for('NewUsers.login'))

services/web/easymail/NewUsers/routes.py
from flask import render_template, url_for, flash, redirect,request,Blueprint
from easymail import app,db,bcrypt
from easymail.NewUsers.forms import LoginForm, RegistrationForm, RequestResetForm, ResetPasswordForm
from easymail.models import User
from flask_login import login_user, current_user, logout_user,login_required
from easymail.NewUsers.utils import generate_confirmation_token, confirm_token,send_email
from flask_mail import Mail, Message
import datetime
NewUsers=Blueprint('NewUsers',__name__)


###### Login Page ##### 
@NewUsers.route('/login',methods=['GET','POST'])

def login():
    error=None
    if current_user.is_authenticated:
        return redirect(url_for('Panel.search'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data) and user.confirmed == True:
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('Panel.search'))
        elif user and bcrypt.check_password_hash(user.password, form.password.data) and user.confirmed == True and user.role=="admin":
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('Admin.admin'))
        else:
            error="Nieprawidłowe hasło lub email"        
    return render_template('auth/login.html', title='Login', form=form,error=error)


###### Register Page ######
@NewUsers.route("/register", methods=['GET', 'POST'])
def register():
    error=None
    if current_user.is_authenticated:
        return redirect(url_for('Panel.search'))
    form = RegistrationForm()
    print("gti")
    if request.method == "POST":
        print("xd")
        if form.validate_on_submit():
            print("elo")
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user = User(name=form.name.data,email=form.email.data, password=hashed_password, confirmed=True)
            db.session.add(user)
            db.session.commit()
        
            return redirect(url_for("NewUsers.login"))
        
    return render_template('auth/register.html', title='Register', form=form,error=error)



@NewUsers.route("/verification/expired/<email>",methods=['GET', 'POST'])
def expired(email):
    token = generate_confirmation_token(email)
    confirm_url = url_for('NewUsers.confirm_email', token=token, _external=True)
    html = render_template('main/email.html', confirm_url=confirm_url)
    subject = "🚨 Zweryfikuj swoje konto | easymailmedical.pl"
    send_email(email, subject, html)
    return redirect(url_for("NewUsers.verification"))

@NewUsers.route("/verification", methods=['GET', 'POST'])
def verification():
    return render_template('main/verification.html',title='Verification')

@NewUsers.route('/confirm/<token>')
def confirm_email(token):
    email = confirm_token(token)
    if email == False:
        flash('Link do weryfikacji wygasł.', 'danger')
        return redirect(url_for('NewUsers.login'))
    else:
        user = User.query.filter_by(email=email).first_or_404()
        if user.confirmed:
            flash('Konto już zweryfikowane', 'success')
        else:
            user.confirmed = True
            user.confirmed_on = datetime.datetime.now()
            db.session.add(user)
            db.session.commit()
            flash('Zweryfikowałeś swoje konto. Dziękujemy!', 'success')
        return redirect(url_for('NewUsers.login'))

######## RESET PASSWORD #######
def send_reset_email(user):
    token = user.get_reset_token()
    reset_link = url_for('NewUsers.reset_token', token=token, _external=True)
    subject = "Resetowanie hasła - easymailmedical.pl"
    html = render_template("main/reset_token_email.html",reset_link=reset_link)
    print(user.email)
    send_email(user.email,subject,html)


@NewUsers.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('Account.panel'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Wysłaliśmy do Ciebie maila z linkiem do resetowania hasła - sprawdź swoją skrzynkę email','success')
        return redirect(url_for('NewUsers.login'))
    return render_template('main/reset_request.html', title='Reset Password', form=form)


@NewUsers.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
 
    if current_user.is_authenticated:
        return redirect(url_for('Account.panel'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Link do resetowania hasła wygasł. Zresetuj hasło jeszcze raz', 'error')
        return redirect(url_for('NewUsers.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Twoje hasło zostało zaktualizowane', 'success')
        return redirect(url_for('NewUsers.login'))
    return render_template('main/reset_password.html', title='Reset Password', form=form)



######## LOGOUT ###########
@NewUsers.route('/logout')
def logout():
    logout_user()
    return redirect('login')

services/web/easymail/Panel/routes.py
from flask import render_template, url_for, flash, redirect,request,Blueprint, send_from_directory,send_file
from easymail import app,db,bcrypt
from easymail.Panel.forms import SearchForm
from easymail.Panel.utils import check_database,create_request,find_emails_in_html
from flask_login import login_user, current_user, logout_user,login_required
from easymail.models import Websites, Emails
import pandas as pd
import time

### Setup blueprint - easier to navigate in the project
Panel=Blueprint('Panel',__name__)
ROWS_PER_PAGE=25
### Endpoints and logic to endpoints - TODO querying database should be only in models file :(
###### Panel Page ##### 
@Panel.route('/emails',methods=['GET','POST'])
@login_required 
def emails():
    page = request.args.get('page',1,type=int)
    mails = Websites.query.join(Emails, Websites.id==Emails.website_id).add_columns(Websites.url,Emails.email, Websites.keyword).filter(Websites.user_id == current_user.id).all()
    keywords = set()
    for mail in mails:
        easy = mail.keyword
        keywords.add(mail.keyword)
    
        
    return render_template('panel/emails.html',mails=mails,keywords=keywords,title="Emials")

@Panel.route('/panel/createCSV/<keyword>',methods=['GET','POST'])
@login_required
def createCSV(keyword):
    mails = Websites.query.join(Emails, Websites.id==Emails.website_id).add_columns(Websites.url,Emails.email, Websites.keyword).filter(Websites.user_id == current_user.id).filter(Websites.keyword==keyword).all()
    name = 'easymail/static/files/'+keyword+str(current_user.id)+'.csv'
    download = 'static/files/'+keyword+str(current_user.id)+'.csv'
    if keyword == "all_master_easy":
        mails = Websites.query.join(Emails, Websites.id==Emails.website_id).add_columns(Websites.url,Emails.email, Websites.keyword).filter(Websites.user_id == current_user.id).all()
        name = 'easymail/static/files/'+"all"+str(current_user.id)+'.csv'
        download = 'static/files/'+"all"+str(current_user.id)+'.csv'
    output = pd.DataFrame()
    for mail in mails:
        mail_dict = {
            "E-mal":mail.email,
             "Keyword":mail.keyword,
            "Url":mail.url,
        }
        output = output.append(mail_dict,ignore_index=True)
   
    output.to_csv(name, encoding='utf-8')
    return send_file(download, as_attachment=True)

@Panel.route('/search',methods=['GET','POST'])
@login_required
def search():
    form = SearchForm()
    mails = None
    if form.validate_on_submit():
        ### Get data from form ###
        keyword = form.keyword.data
        number = str(form.number_of_links.data)
        country = form.country.data
        device = form.device.data
        domain = form.domain.data
        engine = form.engine.data
        
        ### Check if keyword exists in database ###
        database_response = check_database(keyword)
        if database_response == None:
            serp_resp = create_request(keyword,country,number,device,domain,engine)
            for url in serp_resp:
                website = Websites(url=url,keyword=keyword,user_id=current_user.id)
                db.session.add(website)
                db.session.commit()
                website_id = Websites.query.filter_by(url=url).all()
                for id in website_id:
                    emails = find_emails_in_html(url,id.id)
        return redirect(url_for('Panel.emails'))
    return render_template('panel/search.html',form=form,title="Search")

               

services/web/easymail/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_migrate import Migrate
from flask_mail import Mail



import os


app = Flask(__name__)
app.config.from_object("easymail.config.Config")





db = SQLAlchemy(app)
migrate = Migrate(app, db)
mail = Mail()
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
login_manager.login_view = 'NewUsers.login'
mail.init_app(app)

from easymail.Main.routes import Main
from easymail.NewUsers.routes import NewUsers
from easymail.Panel.routes import Panel


app.register_blueprint(Main)
app.register_blueprint(NewUsers)
app.register_blueprint(Panel)

services/web/easymail/templates/panel/emails.html
{% extends 'main.html' %}
{% set active_page = "emails" %}
{% block content %}
<style>
.box-xd:hover{
    cursor:pointer;
    background:lightyellow;
    
}


</style>
<section class="section">

    <div class="input">
        Search
    </div>
</section>
<section class="section">
    <div class="columns">
        <div class="column">
            <p class="text" style="font-size:20px; font-weight:700; color:gold">Your searches<span class="icon is-small is-right" style="margin-right:65px;margin-top:5px; float:right;">
                <a href="{{ url_for('Panel.createCSV',keyword="all_master_easy") }}" class="button is-primary " style="position:relative;float:right">Download All</a>
                 </span></p>

            <br>
           
           
            
           
            {%for keyword in keywords%}
            <div class="box box-xd collapsible"  style="margin-top:10px;font-weight:700px;">{{keyword}} <span class="icon is-small is-right" style="margin-right:65px;margin-top:5px; float:right;">
            <a href="{{ url_for('Panel.createCSV',keyword=keyword) }}" class="button is-primary " style="position:relative;float:right">Download CSV</a>
             </span></div>
             
              <table class="table is-fullwidth " style="display:none;">
                <thead>
                  <tr>
                    
                    <th>Website</th>
                    <th>Email</th>
                    <th>Valid</th>
                    <th>Learn more</th>
                   
                  </tr>
                </thead>
                <tbody >
              
                {% for mail in mails%}
              {%if mail.keyword == keyword%}
                  <tr >
                   
                    <td><a href='{{mail.url}}'>{{mail.url}}  </td>
                   
                    <td><a href='mailto:{{mail.email}}'>{{mail.email}}</a></td>
                    <td style="color:green">True</td>
                    <td>Comming soon</td>
                   
                  </tr>
                  {%endif%}
                 {%endfor%}
                </tbody>
              </table>    
            
             {%endfor%}
         
           
          

           
     
        </div> 
    </div>

</section>
<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "none") {
      content.style.display = "unset";
    } else {
      content.style.display = "none";
    }
  });
}


</script>

{% endblock content %}

services/web/easymail/templates/panel/search.html
{% extends 'main.html' %}
{% set active_page = "search" %}
{% block content %}

<style>
	.lds-hourglass {
		display: inline-block;
		position: relative;
		width: 80px;
		height: 80px;
	  }
	  .lds-hourglass:after {
		content: " ";
		display: block;
		border-radius: 50%;
		width: 0;
		height: 0;
		margin: 8px;
		box-sizing: border-box;
		border: 32px solid #dfc;
		border-color: #dfc transparent #dfc transparent;
		animation: lds-hourglass 1.2s infinite;
	  }
	  @keyframes lds-hourglass {
		0% {
		  transform: rotate(0);
		  animation-timing-function: cubic-bezier(0.55, 0.055, 0.675, 0.19);
		}
		50% {
		  transform: rotate(900deg);
		  animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
		}
		100% {
		  transform: rotate(1800deg);
		}
	  }
	  #fun-fact{
		  display:none;
	  }
	  #loader{
		display:none;
	  }


</style>
<script>
	function loading(){
		var load = document.getElementById("loader")
		var fun = document.getElementById("fun-fact")
	
		load.style.display='block'
		fun.style.display='block'
	}
		
	</script>

	



<section class="section">		
					<div class="column  has-text-left ">
          <form method="POST" action="">
          {{form.hidden_tag()}}
						<div class="field">
							<label class="label">Keyword</label>
							<div class="control">
							{{form.keyword(class="input is-gold",placeholder="Keyword")}}
							</div>
						</div>
            <div class="columns">
            <div class="column">
						<div class="field">
							<label class="label">Number of results</label>
							<div class="control">
							{{form.number_of_links(class="input is-gold",min=1,value=10,placeholder="Number of results")}}
              
							</div>
						</div>
            </div>
                 <div class="column">
						<div class="field">
							<label class="label">Origin country</label>
							<div class="control">
						
              {{form.country(class="input is-gold", type="select")}}
							</div>
						</div>
            </div>
            </div>
              <div class="columns">
            <div class="column">
						<div class="field">
							<label class="label">Device</label>
							<div class="control">
							{{form.device(class="input is-gold",min=1,value=10,placeholder="Number of results")}}
              
							</div>
						</div>
            </div>
             <div class="column">
						<div class="field">
							<label class="label">Domain (ex.google.com)</label>
							<div class="control">
							{{form.domain(class="input is-gold",min=1,value=10,placeholder="Number of results")}}
              
							</div>
						</div>
            </div>
                 <div class="column">
						<div class="field">
							<label class="label">Engine</label>
							<div class="control">
						
              {{form.engine(class="input is-gold", type="select")}}
							</div>
						</div>
            </div>
            </div>
					
						<div class="control" >
							 {{form.submit(class="button is-gold-button",onclick="loading()")}}
							
						</div>
						<div id="loader" class="lds-hourglass" style="margin-left:25vw; margin-top:150px;"></div>
						<div id="fun-fact" style="margin-left:16vw; font-weight:500; ">Do you know that we send over 306.4 billion emails per day?</div>
					</div>
				</div>
			</div>
        </form>
		</div>
	
   
	</section>
	


{% endblock content %}

services/web/easymail/templates/panel/user.html
{% extends 'main.html' %}
{% set active_page = "search" %}
{% block content %}


{%endblock content%}